version: '3'
services:
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8008
    volumes:
      - ./gps_service:/app
    ports:
      - "8008:8008"
    env_file:
      - ./gps_service/.env_prom
    networks:
      - postgres_network_db
    restart: always
networks:
  postgres_network_db:
    external: true